ci: add merge_coverage step

diff --git a/.github/workflows/default.yml b/.github/workflows/default.yml
--- a/.github/workflows/default.yml
+++ b/.github/workflows/default.yml
@@ -990,30 +990,80 @@ jobs:
           cd M2-ISA-R
           source venv/bin/activate
           cd ..
-          python -m m2isar.backends.coverage.coverage_lcov -o rv_par.info --legacy etiss_arch_riscv/gen_model/top.m2isarmodel results_*/coverage/*.csv 2>&1 | tee -a coverage_out.txt
+          python -m m2isar.backends.coverage.coverage_lcov -o rv_par.info --legacy etiss_arch_riscv/gen_model/top.m2isarmodel results_*/coverage/*.csv
           # lcov --rc lcov_branch_coverage=1 -a RV32IMACFD.rv_par.info -a RV64IMACFD.rv_par.info -o RV.info
           lcov --rc lcov_branch_coverage=1 -a ${{ matrix.config.ETISS_ARCH }}.rv_par.info -o RV.info 2>&1 | tee -a coverage_out.txt
-          genhtml -o rv_par --branch-coverage RV.info 2>&1 | tee -a coverage_out.txt
+          genhtml -o rv_par --branch-coverage RV.info 2>&1
       - name: Upload Coverage Report
         uses: actions/upload-artifact@v4
         with:
-          name: coverage-${{ matrix.config.ETISS_ARCH
-            }}-${{ matrix.ubuntu-version }}-${{ env.BUILD_TYPE }}-${{ matrix.toolchain
-            }}-${{ env.LLVM_VERSION }}-${{ env.TC_VERSION }}-${{ env.TC_VARIANT }}-${{
-            matrix.config.ARCH }}-${{ matrix.config.ABI }}-${{ matrix.jit }}JIT
-          path: "*.info"
+          name: coverage-info-${{ matrix.config.ETISS_ARCH }}
+          path: |
+            "*.info"
+            coverage_out.txt
       - name: Upload HTML Coverage Report
         uses: actions/upload-artifact@v4
         with:
-          name: coverage-html-${{ matrix.config.ETISS_ARCH
-            }}-${{ matrix.ubuntu-version }}-${{ env.BUILD_TYPE }}-${{ matrix.toolchain
-            }}-${{ env.LLVM_VERSION }}-${{ env.TC_VERSION }}-${{ env.TC_VARIANT }}-${{
-            matrix.config.ARCH }}-${{ matrix.config.ABI }}-${{ matrix.jit }}JIT
+          name: coverage-html-${{ matrix.config.ETISS_ARCH }}
           path: rv_par
       - name: Add ETISS RISC-V Test Results Summary
         # if: steps.etiss-run-riscv-tests.outcome != 'success'
         run: |
           echo "### ETISS Coverage Report" >> $GITHUB_STEP_SUMMARY
+          echo >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+          cat coverage_out.txt >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+          echo >> $GITHUB_STEP_SUMMARY
+      - name: Cleanup
+        if: success()
+        run: rm -f *_out.txt results_* *.info rv_par || true
+  merge_coverage:
+    needs: [check, report_coverage]
+    strategy:
+      fail-fast: false
+      # fail-fast: true
+      matrix:
+        ubuntu-version: [22.04]
+        python-version: ['3.10']
+    runs-on: ubuntu-${{ matrix.ubuntu-version }}
+    steps:
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Install APT dependencies
+        run: |
+          sudo apt update
+          sudo apt -qq install -y python3-pip python3-venv lcov
+      - name: Download Coverage Artifacts
+        uses: actions/download-artifact@v5
+        with:
+          pattern: "coverage-info-*"
+      - name: Merge Coverage Reports
+        run: |
+          genhtml --version
+          # lcov --rc lcov_branch_coverage=1 -a RV32IMACFD.rv_par.info -a RV64IMACFD.rv_par.info -o RV.info
+          LCOV_ARGS=""
+          lcov --rc lcov_branch_coverage=1 $LCOV_ARGS -o RV.info 2>&1 | tee -a coverage_out.txt
+          rm -rf rv_par/ RV.info
+          genhtml -o rv_par --branch-coverage RV.info 2>&1
+      - name: Upload Coverage Report
+        uses: actions/upload-artifact@v4
+        with:
+          name: coverage-info-merged
+          path: |
+            "*.info"
+            coverage_out.txt
+      - name: Upload HTML Coverage Report
+        uses: actions/upload-artifact@v4
+        with:
+          name: coverage-html-merged-${{ matrix.ubuntu-version }}
+          path: rv_par
+      - name: Add ETISS RISC-V Test Results Summary
+        # if: steps.etiss-run-riscv-tests.outcome != 'success'
+        run: |
+          echo "### Merged ETISS Coverage Report" >> $GITHUB_STEP_SUMMARY
           echo >> $GITHUB_STEP_SUMMARY
           echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
           cat coverage_out.txt >> $GITHUB_STEP_SUMMARY
@@ -1159,7 +1209,7 @@ jobs:
           # force: true
   publish:
     if: ${{ github.event.client_payload.is_pr != 'true' && github.event.client_payload.from == '' }}
-    needs: [setup_etiss, finalize]
+    needs: [setup_etiss, finalize, merge_coverage]
     runs-on: ubuntu-latest
     steps:
       - name: Set up Python
@@ -1182,6 +1232,8 @@ jobs:
           ls artifacts/*
           ls artifacts/etiss-patch-*/etiss.patch && PATCH_EXISTS=1 || PATCH_EXISTS=0
           echo "PATCH_EXISTS=$PATCH_EXISTS" >> $GITHUB_OUTPUT
+          echo "COVERAGE_SUMMARY:"
+          cat artifacts/coverage-info-merged/coverage_out.txt
       - name: Clone ETISS
         if: ${{ steps.check_patch.outputs.PATCH_EXISTS != '0' }}
         uses: actions/checkout@v4
