ci: add composite action run-examples

diff --git a/.github/workflows/default.yml b/.github/workflows/default.yml
--- a/.github/workflows/default.yml
+++ b/.github/workflows/default.yml
@@ -634,41 +634,56 @@ jobs:
             }}-${{ matrix.config.ETISS_ARCH }}-OFF-${{ needs.check.outputs.etiss_riscv_tests_ref
             }}
           path: etiss/build/install
-      - name: Run Examples on ${{ matrix.config.ETISS_ARCH }}
-        if: success()
-        id: etiss-run-sw
+      # - name: Run Examples on ${{ matrix.config.ETISS_ARCH }}
+      #   if: success()
+      #   id: etiss-run-sw
+      #   continue-on-error: true
+      #   run: |
+      #     ls
+      #     ls etiss/build/install
+      #     set -o pipefail
+      #     TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
+      #     chmod +x etiss/build/install/bin/bare_etiss_processor
+      #     for prog in $(echo ${{ env.PROGS }} | sed 's/,/ /g'); do
+      #         echo "--- Program: $prog ---" | tee -a etiss_sw_run_out.txt
+      #         timeout 5m etiss/build/install/bin/bare_etiss_processor -ietiss_riscv_examples/build/install/ini/$prog.ini --arch.cpu=${{ matrix.config.ETISS_ARCH }} --jit.type=${{ matrix.jit }}JIT --vp.stats_file_path=stats.json 2>&1 | tee -a etiss_sw_run_out.txt
+      #         if [[ -f stats.json ]]
+      #         then
+      #             jq -s "[.[] + {prog: \"$prog\", toolchain: \"${{ matrix.toolchain }}\", jit: \"${{ matrix.jit}}\", etiss_arch: \"${{ matrix.config.ETISS_ARCH }}\", arch: \"${{ matrix.config.ARCH }}\", abi: \"${{ matrix.config.ABI }}\", timestamp: \"$TIMESTAMP\", env_sha: \"${{ github.sha }}\", etiss_sha: \"${{ needs.check.outputs.etiss_ref }}\"}]" stats.json > stats_$prog.json
+      #             rm stats.json
+      #         fi
+      #     done
+      #     jq -s '[.[][]?]' stats*.json > combined_stats.json
+      #     set +o pipefail
+      #     ./scripts/json_metrics2markdown.sh combined_stats.json > combined_stats.md
+      # - name: Add ETISS SW Run Summary (Failure)
+      #   if: ${{ steps.etiss-run-sw.outcome != 'success' }}
+      #   run: |
+      #     echo "### ETISS SW Run Status" >> $GITHUB_STEP_SUMMARY
+      #     echo "FAILING :x:" >> $GITHUB_STEP_SUMMARY
+      #     echo >> $GITHUB_STEP_SUMMARY
+      #     echo "**ETISS Sim Outputs:**" >> $GITHUB_STEP_SUMMARY
+      #     echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+      #     cat etiss_sw_run_out.txt >> $GITHUB_STEP_SUMMARY
+      #     echo >> $GITHUB_STEP_SUMMARY
+      #     echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+      #     echo >> $GITHUB_STEP_SUMMARY
+      #     exit 1
+      - name: Run Examples
+        id: run-examples
         continue-on-error: true
-        run: |
-          ls
-          ls etiss/build/install
-          set -o pipefail
-          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
-          chmod +x etiss/build/install/bin/bare_etiss_processor
-          for prog in $(echo ${{ env.PROGS }} | sed 's/,/ /g'); do
-              echo "--- Program: $prog ---" | tee -a etiss_sw_run_out.txt
-              timeout 5m etiss/build/install/bin/bare_etiss_processor -ietiss_riscv_examples/build/install/ini/$prog.ini --arch.cpu=${{ matrix.config.ETISS_ARCH }} --jit.type=${{ matrix.jit }}JIT --vp.stats_file_path=stats.json 2>&1 | tee -a etiss_sw_run_out.txt
-              if [[ -f stats.json ]]
-              then
-                  jq -s "[.[] + {prog: \"$prog\", toolchain: \"${{ matrix.toolchain }}\", jit: \"${{ matrix.jit}}\", etiss_arch: \"${{ matrix.config.ETISS_ARCH }}\", arch: \"${{ matrix.config.ARCH }}\", abi: \"${{ matrix.config.ABI }}\", timestamp: \"$TIMESTAMP\", env_sha: \"${{ github.sha }}\", etiss_sha: \"${{ needs.check.outputs.etiss_ref }}\"}]" stats.json > stats_$prog.json
-                  rm stats.json
-              fi
-          done
-          jq -s '[.[][]?]' stats*.json > combined_stats.json
-          set +o pipefail
-          ./scripts/json_metrics2markdown.sh combined_stats.json > combined_stats.md
-      - name: Add ETISS SW Run Summary (Failure)
-        if: ${{ steps.etiss-run-sw.outcome != 'success' }}
-        run: |
-          echo "### ETISS SW Run Status" >> $GITHUB_STEP_SUMMARY
-          echo "FAILING :x:" >> $GITHUB_STEP_SUMMARY
-          echo >> $GITHUB_STEP_SUMMARY
-          echo "**ETISS Sim Outputs:**" >> $GITHUB_STEP_SUMMARY
-          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-          cat etiss_sw_run_out.txt >> $GITHUB_STEP_SUMMARY
-          echo >> $GITHUB_STEP_SUMMARY
-          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-          echo >> $GITHUB_STEP_SUMMARY
-          exit 1
+        uses: ./.github/actions/run-examples
+        with:
+          enable-summary: true
+          examples-dir: ${{ github.workspace }}/etiss_riscv_examples
+          etiss-install-dir: ${{ github.workspace }}/etiss/build/install
+          etiss-arch: ${{ matrix.config.ETISS_ARCH }}
+          arch: ${{ matrix.config.ARCH }}
+          abi: ${{ matrix.config.ABI }}
+          toolchain: ${{ matrix.toolchain }}
+          progs: ${{ env.PROGS }}
+          env_ref: ${{ github.sha }}
+          etiss_ref: ${{ needs.check.outputs.etiss_ref }}
       - name: Upload ETISS Outputs
         if: ${{ success() || failure() }}
         uses: actions/upload-artifact@v7
@@ -689,12 +704,6 @@ jobs:
           path: |
             combined_stats.json
             combined_stats.md
-      - name: Add ETISS SW Run Summary (Metrics)
-        if: ${{ steps.etiss-run-sw.outcome == 'success' }}
-        run: |
-          echo "### ETISS SW Run Metrics" >> $GITHUB_STEP_SUMMARY
-          cat combined_stats.md >> $GITHUB_STEP_SUMMARY
-          echo >> $GITHUB_STEP_SUMMARY
   setup_tests:
     outputs:
       output1: ${{ steps.step1.outputs.test }}
